import { useEffect, useRef, useState } from 'react';
import { MapPin, AlertCircle } from 'lucide-react';
import COLORS from '../../constants/colors';

/**
 * DeliveryMap — renders the shipment's route on a real Google Map.
 *
 * The route coordinates are mock (generated by the tracking service), but the
 * map tiles are real. Shows the fulfilment centre (origin), the delivery
 * destination, a connecting route line, and an animated marker for the parcel's
 * live position, which slides forward as the order advances dispatched →
 * delivered.
 *
 * Requires VITE_GOOGLE_MAPS_API_KEY. Without it, renders a graceful fallback so
 * the rest of the tracking page still works.
 *
 * @param {{
 *   origin?: {lat:number,lng:number,label?:string},
 *   destination?: {lat:number,lng:number,label?:string},
 *   current?: {lat:number,lng:number,label?:string},
 *   status?: string,
 * }} props
 */

const MAPS_KEY = import.meta.env.VITE_GOOGLE_MAPS_API_KEY || '';

let _mapsPromise = null;

/** Load the Google Maps JS API once. Resolves with window.google or rejects. */
function loadGoogleMaps() {
  if (window.google?.maps) return Promise.resolve(window.google);
  if (_mapsPromise) return _mapsPromise;

  _mapsPromise = new Promise((resolve, reject) => {
    if (!MAPS_KEY) {
      reject(new Error('missing-key'));
      return;
    }
    const script = document.createElement('script');
    script.src = `https://maps.googleapis.com/maps/api/js?key=${MAPS_KEY}`;
    script.async = true;
    script.defer = true;
    script.onload = () =>
      window.google?.maps ? resolve(window.google) : reject(new Error('load-failed'));
    script.onerror = () => reject(new Error('load-failed'));
    document.head.appendChild(script);
  });
  return _mapsPromise;
}

// A simple parcel/truck marker icon (SVG data URI).
function truckIcon(google) {
  return {
    path: google.maps.SymbolPath.CIRCLE,
    scale: 8,
    fillColor: COLORS.brass || '#b5853a',
    fillOpacity: 1,
    strokeColor: '#fdf6e6',
    strokeWeight: 3,
  };
}

function DeliveryMap({ origin, destination, current, status }) {
  const mapRef = useRef(null);
  const mapObj = useRef(null);
  const markers = useRef({ origin: null, dest: null, parcel: null, line: null });
  const animRef = useRef(null);
  const [error, setError] = useState('');

  // Initialise the map once the script + coordinates are ready.
  useEffect(() => {
    let cancelled = false;
    if (!origin || !destination) return undefined;

    loadGoogleMaps()
      .then((google) => {
        if (cancelled || !mapRef.current) return;

        const map = new google.maps.Map(mapRef.current, {
          disableDefaultUI: true,
          zoomControl: true,
          gestureHandling: 'cooperative',
          styles: MAP_STYLE,
        });
        mapObj.current = map;

        // Fit both endpoints in view.
        const bounds = new google.maps.LatLngBounds();
        bounds.extend(origin);
        bounds.extend(destination);
        map.fitBounds(bounds, 64);

        // Origin (store) + destination (home) markers.
        markers.current.origin = new google.maps.Marker({
          position: origin, map, title: origin.label || 'Fulfilment centre',
          icon: {
            path: google.maps.SymbolPath.CIRCLE, scale: 6,
            fillColor: COLORS.cloth || '#6b4f3a', fillOpacity: 1,
            strokeColor: '#fdf6e6', strokeWeight: 2,
          },
        });
        markers.current.dest = new google.maps.Marker({
          position: destination, map, title: destination.label || 'Destination',
          icon: {
            path: 'M12 2C8.1 2 5 5.1 5 9c0 5.2 7 13 7 13s7-7.8 7-13c0-3.9-3.1-7-7-7z',
            fillColor: COLORS.error || '#b4452f', fillOpacity: 1,
            strokeColor: '#fdf6e6', strokeWeight: 1.5,
            scale: 1.6, anchor: new google.maps.Point(12, 22),
          },
        });

        // Route line.
        markers.current.line = new google.maps.Polyline({
          path: [origin, destination], map,
          geodesic: true,
          strokeColor: COLORS.brass || '#b5853a',
          strokeOpacity: 0.7, strokeWeight: 3,
        });

        // Parcel marker at the live position.
        markers.current.parcel = new google.maps.Marker({
          position: current || origin, map,
          icon: truckIcon(google), zIndex: 999,
          title: 'Your parcel',
        });
      })
      .catch((err) => {
        if (!cancelled) setError(err.message || 'load-failed');
      });

    return () => {
      cancelled = true;
      if (animRef.current) cancelAnimationFrame(animRef.current);
    };
    // Re-init only when endpoints change (rare).
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [origin?.lat, origin?.lng, destination?.lat, destination?.lng]);

  // Animate the parcel marker forward whenever the live position changes.
  useEffect(() => {
    const google = window.google;
    const parcel = markers.current.parcel;
    if (!google || !parcel || !current) return undefined;

    const start = parcel.getPosition();
    if (!start) {
      parcel.setPosition(current);
      return undefined;
    }
    const from = { lat: start.lat(), lng: start.lng() };
    const to = current;
    const duration = 1200;
    const t0 = performance.now();

    const step = (now) => {
      const p = Math.min((now - t0) / duration, 1);
      const eased = p < 0.5 ? 2 * p * p : 1 - Math.pow(-2 * p + 2, 2) / 2; // easeInOutQuad
      parcel.setPosition({
        lat: from.lat + (to.lat - from.lat) * eased,
        lng: from.lng + (to.lng - from.lng) * eased,
      });
      if (p < 1) animRef.current = requestAnimationFrame(step);
    };
    animRef.current = requestAnimationFrame(step);

    return () => {
      if (animRef.current) cancelAnimationFrame(animRef.current);
    };
  }, [current?.lat, current?.lng]);

  // ── Fallbacks ────────────────────────────────────────────
  if (!origin || !destination) return null;

  if (error === 'missing-key') {
    return (
      <div
        className="rounded-lg p-4 mb-4 flex items-center gap-2 text-sm"
        style={{ backgroundColor: COLORS.surfaceLight, color: COLORS.text.tertiary, border: `1px dashed ${COLORS.border}` }}
      >
        <MapPin size={15} style={{ color: COLORS.brass }} />
        Map preview unavailable — set VITE_GOOGLE_MAPS_API_KEY to show the live route.
      </div>
    );
  }
  if (error) {
    return (
      <div
        className="rounded-lg p-4 mb-4 flex items-center gap-2 text-sm"
        style={{ backgroundColor: COLORS.surfaceLight, color: COLORS.text.tertiary, border: `1px solid ${COLORS.border}` }}
      >
        <AlertCircle size={15} style={{ color: COLORS.error }} />
        Couldn't load the map right now.
      </div>
    );
  }

  return (
    <div className="mb-4">
      <div
        ref={mapRef}
        className="w-full rounded-lg overflow-hidden"
        style={{ height: 240, border: `1px solid ${COLORS.border}` }}
      />
      {current?.label && (
        <p className="text-xs mt-1.5 flex items-center gap-1.5" style={{ color: COLORS.text.tertiary }}>
          <MapPin size={12} style={{ color: COLORS.brass }} />
          {status === 'delivered' ? 'Delivered to' : 'Currently'}: {current.label}
        </p>
      )}
    </div>
  );
}

// Subtle warm/dark map theme to match the Folio palette.
const MAP_STYLE = [
  { elementType: 'geometry', stylers: [{ color: '#2b2620' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#2b2620' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#b9a88f' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#1f1b16' }] },
  { featureType: 'road', elementType: 'geometry', stylers: [{ color: '#3a332b' }] },
  { featureType: 'poi', stylers: [{ visibility: 'off' }] },
  { featureType: 'transit', stylers: [{ visibility: 'off' }] },
  { featureType: 'administrative', elementType: 'geometry', stylers: [{ color: '#4a4035' }] },
];

export default DeliveryMap;
